### ISSUE TITLE
What to do?

### ISSUE THREAD

**Issue by Nanobot123** [dejanra/RTC_alarm_clock#1]
Arduino: 1.6.12 (Windows 8.1), Vývojová deska: "Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

In file included from C:\Users\Dominik\Desktop\RTC_alarm_clock-master\RTC_alarm_clock-master\Arduino_DS3231\Arduino_DS3231.ino:26:0:

C:\Users\Dominik\Documents\Arduino\libraries\DS3232RTC-master/DS3232RTC.h:136:26: error: 'tmElements_t' has not been declared

         static byte read(tmElements_t &tm);

                          ^

C:\Users\Dominik\Documents\Arduino\libraries\DS3232RTC-master/DS3232RTC.h:137:20: error: 'tmElements_t' has not been declared

         byte write(tmElements_t &tm);

                    ^

C:\Users\Dominik\Desktop\RTC_alarm_clock-master\RTC_alarm_clock-master\Arduino_DS3231\Arduino_DS3231.ino: In function 'void setup()':

Arduino_DS3231:207: error: 'setSyncProvider' was not declared in this scope

     setSyncProvider(RTC.get);               // set RTC as the Syncprovider

                            ^

Arduino_DS3231:208: error: 'setSyncInterval' was not declared in this scope

     setSyncInterval(5);                     // time in sec of resync with RTC

                      ^

C:\Users\Dominik\Desktop\RTC_alarm_clock-master\RTC_alarm_clock-master\Arduino_DS3231\Arduino_DS3231.ino: In function 'void display_date()':

Arduino_DS3231:758: error: 'weekday' was not declared in this scope

 DoW= weekday(); 

              ^

C:\Users\Dominik\Desktop\RTC_alarm_clock-master\RTC_alarm_clock-master\Arduino_DS3231\Arduino_DS3231.ino: In function 'void check_RTC()':

Arduino_DS3231:1084: error: 'timeStatus' was not declared in this scope

     if (timeStatus() != timeSet) 

                    ^

Arduino_DS3231:1084: error: 'timeSet' was not declared in this scope

     if (timeStatus() != timeSet) 

                         ^

Byly nalezené násobné knihovny "LiquidCrystal_I2C.h"
 Použitý: C:\Users\Dominik\Documents\Arduino\libraries\LiquidCrystal_I2C
 Nepoužitý: C:\Users\Dominik\Documents\Arduino\libraries\Arduino-LiquidCrystal-I2C-library-master
Byly nalezené násobné knihovny "Button.h"
 Použitý: C:\Users\Dominik\Documents\Arduino\libraries\Button-master
 Nepoužitý: C:\Programy\Arduino\libraries\Button-master
Byly nalezené násobné knihovny "DS3232RTC.h"
 Použitý: C:\Users\Dominik\Documents\Arduino\libraries\DS3232RTC-master
 Nepoužitý: C:\Programy\Arduino\libraries\DS3232RTC-master
Byly nalezené násobné knihovny "Streaming.h"
 Použitý: C:\Users\Dominik\Documents\Arduino\libraries\Streaming
 Nepoužitý: C:\Programy\Arduino\libraries\Streaming
exit status 1
'setSyncProvider' was not declared in this scope

Táto zpráva by měla mít víc informacií v
"Zobrazení podrobného výstupu při kompilaci"
podle zapnuté volby v Soubor -> Nastavení.

Please help

**Comment by dejanra** [comment]
Hi! Please use Arduino IDE 1.6.5 (or 1.6.6) for compile (but it should be work with new 1.8.1 version). Use only library from link in 'code'!
If you still have a problem, please delete all libraray in C:>documents>Arduino>library, then UNINSTALL Arduino IDE and install again Arduino IDE 1.6.5 and then add library again.
